# Etapa de build
FROM node:18-slim AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Etapa final com Alpine
FROM node:18-alpine

WORKDIR /app

# Copia arquivos buildados do React
COPY --from=builder /app/build ./build

# Instala servidor estático
RUN npm install -g serve

EXPOSE 3000

# Comando para servir os arquivos
CMD ["serve", "-s", "build", "-l", "3000"]
