version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "80:80" # apenas se não tiver proxy reverso externo
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: nest_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # - outras variáveis (JWT_SECRET, DATABASE_URL...) via .env ou direto aqui
    volumes:
      - ./backend/ssl:/app/ssl
      - ./backend/file:/app/file
# Se você estiver usando Caddy como proxy reverso externo (fora dos containers),
# pode remover a parte `ports` do frontend e backend e expor por rede interna (bridge)
