services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    volumes:
      - ./backend/ssl:/app/ssl
      - ./backend/file:/app/file
