# Etapa de build
FROM node:18-slim AS builder

WORKDIR /app

COPY package*.json ./
COPY file/ /app/file/
COPY ssl/ /app/ssl/
RUN npm ci

COPY . .
RUN npm run build

# Etapa final
FROM node:18-slim

WORKDIR /app

# Instala apenas os componentes essenciais do LibreOffice
RUN apt-get update && apt-get install -y \
    libreoffice-core \
    libreoffice-writer \
    fonts-dejavu \
    dumb-init \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Verifica se LibreOffice está funcional
RUN libreoffice --headless --version >/dev/null 2>&1

# Copia os artefatos de build e instala dependências
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/file ./file
COPY --from=builder /app/ssl ./ssl


# Cria e configura o usuário seguro
RUN chown -R node:node /app
USER node

EXPOSE 8080
ENTRYPOINT ["dumb-init", "--"]
COPY .env .env
CMD ["node", "dist/main.js"]
