name: Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acesso SSH e deploy na VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy

            # Se o repositório ainda não existir na VM, clona
            if [ ! -d ".git" ]; then
              git clone https://github.com/Simposiofatec/simtefac.git .
            else
              git reset --hard
              git pull origin dev
            fi

            # Sobe containers já buildando com os Dockerfiles do repo
            docker compose up -d --build
