name: Pipeline

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Acesso SSH e deploy na VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/deploy

            # Se não existir .git, clona normalmente em um subdiretório
            if [ ! -d ".git" ]; then
              git clone https://github.com/Simposiofatec/simtefac.git repo
            fi

            cd repo

            # Sempre garante que o branch está atualizado
            git fetch origin
            git reset --hard origin/dev

            # Sobe os containers
            docker compose up -d --build
