name: Deploy Frontend Estático via SCP

on:
  push:
    branches:
      - main
    paths:
      - 'Front-end/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências e gerar build (se necessário)
        run: |
          cd ./Front-end
          npm install
          npm run build

      - name: Enviar arquivos para a VM via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "Front-end/build/**" 
          target: "/var/www/react-app"
          strip_components: 2

      - name: Reiniciar Caddy (opcional)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo systemctl reload caddy
